title: 홍성혁의 블로그
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: https://github.com/hsh03/hsh03.github.io.git
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about

social:
   github: brianmaierjr
   twitter: brianmaierjr
   facebook: 홍성혁
   email: mickey030427@gmail.com
